<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.226 (unknown)" debug="no" mameconfig="10">
	<machine name="zaxxon" sourcefile="zaxxon.cpp" sampleof="zaxxon">
		<description>Zaxxon (set 1, rev D)</description>
		<year>1982</year>
		<manufacturer>Sega</manufacturer>
		<rom name="zaxxon_rom3d.u27" size="8192" crc="6e2b4a30" sha1="80ac53c554c84226b119cbe3cf3470bcdbcd5762" region="maincpu" offset="0"/>
		<rom name="zaxxon_rom2d.u28" size="8192" crc="1c9ea398" sha1="0cd259be3fa80f3d53dfa76d5ca06773cdfe5945" region="maincpu" offset="2000"/>
		<rom name="zaxxon_rom1d.u29" size="4096" crc="1c123ef9" sha1="2588be06ea7baca6112d58c78a1eeb98aad8a02e" region="maincpu" offset="4000"/>
		<rom name="zaxxon_rom14.u68" size="2048" crc="07bf8c52" sha1="425157a1625b1bd5169c3218b958010bf6af12bb" region="gfx_tx" offset="0"/>
		<rom name="zaxxon_rom15.u69" size="2048" crc="c215edcb" sha1="f1ded2173eb139f48d2ca86c5ef00acbe6c11cd3" region="gfx_tx" offset="800"/>
		<rom name="zaxxon_rom6.u113" size="8192" crc="6e07bb68" sha1="a002f3441b0f0044615ce71ecbd14edadba16270" region="gfx_bg" offset="0"/>
		<rom name="zaxxon_rom5.u112" size="8192" crc="0a5bce6a" sha1="a86543727389931244ba8a576b543d7ac05a2585" region="gfx_bg" offset="2000"/>
		<rom name="zaxxon_rom4.u111" size="8192" crc="a5bf1465" sha1="a8cd27dfb4a606bae8bfddcf936e69e980fb1977" region="gfx_bg" offset="4000"/>
		<rom name="zaxxon_rom11.u77" size="8192" crc="eaf0dd4b" sha1="194e2ca0a806e0cb6bb7cc8341d1fc6f2ea911f6" region="gfx_spr" offset="0"/>
		<rom name="zaxxon_rom12.u78" size="8192" crc="1c5369c7" sha1="af6a5984c3cedfa8c9efcd669f4f205b51a433b2" region="gfx_spr" offset="2000"/>
		<rom name="zaxxon_rom13.u79" size="8192" crc="ab4e8a9a" sha1="4ac79cccc30e4adfa878b36101e97e20ac010438" region="gfx_spr" offset="4000"/>
		<rom name="zaxxon_rom8.u91" size="8192" crc="28d65063" sha1="e1f90716236c61df61bdc6915a8e390cb4dcbf15" region="tilemap_dat" offset="0"/>
		<rom name="zaxxon_rom7.u90" size="8192" crc="6284c200" sha1="d26a9049541479b8b19f5aa0690cf4aaa787c9b5" region="tilemap_dat" offset="2000"/>
		<rom name="zaxxon_rom10.u93" size="8192" crc="a95e61fd" sha1="a0f8c15ff75affa3532abf8f340811cf415421fd" region="tilemap_dat" offset="4000"/>
		<rom name="zaxxon_rom9.u92" size="8192" crc="7e42691f" sha1="2124363be8f590b74e2b15dd3f90d77dd9ca9528" region="tilemap_dat" offset="6000"/>
		<rom name="mro16.u76" size="256" crc="6cc6695b" sha1="01ae8450ccc302e1a5ae74230d44f6f531a962e2" region="proms" offset="0"/>
		<rom name="zaxxon.u72" size="256" crc="deaa21f7" sha1="0cf08fb62f77d93ff7cb883c633e0db35906e11d" region="proms" offset="100"/>
		<device_ref name="z80"/>
		<device_ref name="i8255"/>
		<device_ref name="ls259"/>
		<device_ref name="ls259"/>
		<device_ref name="gfxdecode"/>
		<device_ref name="palette"/>
		<device_ref name="screen"/>
		<device_ref name="speaker"/>
		<device_ref name="samples"/>
		<sample name="03"/>
		<sample name="02"/>
		<sample name="01"/>
		<sample name="00"/>
		<sample name="11"/>
		<sample name="10"/>
		<sample name="08"/>
		<sample name="23"/>
		<sample name="21"/>
		<sample name="20"/>
		<sample name="05"/>
		<sample name="04"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="3041250"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="samples" name="Samples"/>
		<display tag="screen" type="raster" rotate="90" width="256" height="224" refresh="59.999408" pixclock="6082500" htotal="384" hbend="0" hbstart="256" vtotal="264" vbend="16" vbstart="240" />
		<sound channels="1"/>
		<input players="2" coins="2" service="yes">
			<control type="joy" player="1" buttons="1" ways="8"/>
			<control type="joy" player="2" buttons="1" ways="8"/>
		</input>
		<dipswitch name="Bonus Life" tag="DSW02" mask="3">
			<diplocation name="SW1" number="1" inverted="yes"/>
			<diplocation name="SW1" number="2" inverted="yes"/>
			<dipvalue name="10000" value="3" default="yes"/>
			<dipvalue name="20000" value="1"/>
			<dipvalue name="30000" value="2"/>
			<dipvalue name="40000" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSW02" mask="4">
			<diplocation name="SW1" number="3" inverted="yes"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="4" default="yes"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSW02" mask="8">
			<diplocation name="SW1" number="4" inverted="yes"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Lives" tag="DSW02" mask="48">
			<diplocation name="SW1" number="5" inverted="yes"/>
			<diplocation name="SW1" number="6" inverted="yes"/>
			<dipvalue name="3" value="48" default="yes"/>
			<dipvalue name="4" value="16"/>
			<dipvalue name="5" value="32"/>
			<dipvalue name="Free Play" value="0"/>
		</dipswitch>
		<dipswitch name="Sound" tag="DSW02" mask="64">
			<diplocation name="SW1" number="7" inverted="yes"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="64" default="yes"/>
		</dipswitch>
		<dipswitch name="Cabinet" tag="DSW02" mask="128">
			<diplocation name="SW1" number="8" inverted="yes"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="128"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSW03" mask="15">
			<diplocation name="SW2" number="1" inverted="yes"/>
			<diplocation name="SW2" number="2" inverted="yes"/>
			<diplocation name="SW2" number="3" inverted="yes"/>
			<diplocation name="SW2" number="4" inverted="yes"/>
			<dipvalue name="4 Coins/1 Credit" value="15"/>
			<dipvalue name="3 Coins/1 Credit" value="7"/>
			<dipvalue name="2 Coins/1 Credit" value="11"/>
			<dipvalue name="2C/1C 5C/3C 6C/4C" value="6"/>
			<dipvalue name="2C/1C 3C/2C 4C/3C" value="10"/>
			<dipvalue name="1 Coin/1 Credit" value="3" default="yes"/>
			<dipvalue name="1C/1C 5C/6C" value="2"/>
			<dipvalue name="1C/1C 4C/5C" value="12"/>
			<dipvalue name="1C/1C 2C/3C" value="4"/>
			<dipvalue name="1 Coin/2 Credits" value="13"/>
			<dipvalue name="1C/2C 5C/11C" value="8"/>
			<dipvalue name="1C/2C 4C/9C" value="0"/>
			<dipvalue name="1 Coin/3 Credits" value="5"/>
			<dipvalue name="1 Coin/4 Credits" value="9"/>
			<dipvalue name="1 Coin/5 Credits" value="1"/>
			<dipvalue name="1 Coin/6 Credits" value="14"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSW03" mask="240">
			<diplocation name="SW2" number="5" inverted="yes"/>
			<diplocation name="SW2" number="6" inverted="yes"/>
			<diplocation name="SW2" number="7" inverted="yes"/>
			<diplocation name="SW2" number="8" inverted="yes"/>
			<dipvalue name="4 Coins/1 Credit" value="240"/>
			<dipvalue name="3 Coins/1 Credit" value="112"/>
			<dipvalue name="2 Coins/1 Credit" value="176"/>
			<dipvalue name="2C/1C 5C/3C 6C/4C" value="96"/>
			<dipvalue name="2C/1C 3C/2C 4C/3C" value="160"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="1C/1C 5C/6C" value="32"/>
			<dipvalue name="1C/1C 4C/5C" value="192"/>
			<dipvalue name="1C/1C 2C/3C" value="64"/>
			<dipvalue name="1 Coin/2 Credits" value="208"/>
			<dipvalue name="1C/2C 5C/11C" value="128"/>
			<dipvalue name="1C/2C 4C/9C" value="0"/>
			<dipvalue name="1 Coin/3 Credits" value="80"/>
			<dipvalue name="1 Coin/4 Credits" value="144"/>
			<dipvalue name="1 Coin/5 Credits" value="16"/>
			<dipvalue name="1 Coin/6 Credits" value="224"/>
		</dipswitch>
		<port tag=":COIN">
		</port>
		<port tag=":DSW02">
		</port>
		<port tag=":DSW03">
		</port>
		<port tag=":SERVICESW">
		</port>
		<port tag=":SW00">
		</port>
		<port tag=":SW01">
		</port>
		<port tag=":SW100">
		</port>
		<driver status="imperfect" emulation="good" savestate="supported"/>
		<feature type="sound" status="imperfect"/>
	</machine>
	<machine name="gfxdecode" sourcefile="src/emu/drawgfx.cpp" isdevice="yes" runnable="no">
		<description>gfxdecode</description>
	</machine>
	<machine name="i8255" sourcefile="src/devices/machine/i8255.cpp" isdevice="yes" runnable="no">
		<description>Intel 8255 PPI</description>
	</machine>
	<machine name="ls259" sourcefile="src/devices/machine/74259.cpp" isdevice="yes" runnable="no">
		<description>74LS259 Addressable Latch</description>
	</machine>
	<machine name="palette" sourcefile="src/emu/emupal.cpp" isdevice="yes" runnable="no">
		<description>palette</description>
	</machine>
	<machine name="samples" sourcefile="src/devices/sound/samples.cpp" isdevice="yes" runnable="no">
		<description>Samples</description>
		<sound channels="0"/>
	</machine>
	<machine name="screen" sourcefile="src/emu/screen.cpp" isdevice="yes" runnable="no">
		<description>Video Screen</description>
	</machine>
	<machine name="speaker" sourcefile="src/emu/speaker.cpp" isdevice="yes" runnable="no">
		<description>Speaker</description>
		<sound channels="1"/>
	</machine>
	<machine name="z80" sourcefile="src/devices/cpu/z80/z80.cpp" isdevice="yes" runnable="no">
		<description>Zilog Z80</description>
	</machine>
</mame>
